/**
 * Screen 7: Agent Chat & Swarm Activity
 * Chat UI with real-time agent-activity side panel displaying active agents
 * (Document, Tax Engine, Compliance, Planning, Research, Verifier) with step traces.
 * Grounded answers with citation chips, confidence scores, and "Flag for CA review" action.
 * Streaming-style rendering and suggested prompts.
 */

import React, { useState, useRef, useEffect } from 'react';
import {
  MessageSquare,
  Send,
  Cpu,
  ShieldCheck,
  AlertTriangle,
  Flag,
  Sparkles,
  CheckCircle2,
  Clock,
} from 'lucide-react';
import { useApp } from '../context/AppContext';
import { AIChatService } from '../services/aiChatService';
import { ChatMessage, AgentStepTrace } from '../types';
import { StatusBadge, CitationChip } from '../components/common/StatusBadges';
import { PageHeader } from '../components/common/PageHeader';
import { JourneyStepper } from '../components/common/JourneyStepper';
import { NextActionCard } from '../components/common/NextActionCard';

const SUGGESTED_PROMPTS = [
  'Which regime saves me more tax for FY 2025-26 and why?',
  'What happens if my company starts contributing 10% to NPS under Sec 80CCD(2)?',
  'How is my ₹1,80,000 mutual fund LTCG taxed under the new 12.5% rate?',
  'Can I claim HRA and Home Loan interest simultaneously?',
  'Why did the Verifier Agent flag co-ownership in my housing loan certificate?',
];

export const AgentChat: React.FC = () => {
  const { activeClient } = useApp();

  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: 'msg-initial',
      sender: 'agent',
      agentName: 'CAdesk Multi-Agent Team',
      text: `Hello ${activeClient.name}. I am your multi-agent tax team. Document, Tax, Compliance, and Verifier agents are synchronized with your FY 2025-26 working papers.\n\nAll tax figures are strictly generated by our deterministic engine—not hallucinated by language models. How can we support your tax planning today?`,
      timestamp: '10:00 AM',
      structuredResponse: {
        answer: '',
        agentName: 'CAdesk Multi-Agent Team',
        confidence: 99,
        requiresHumanReview: false,
        citations: [
          { section: '115BAC(1A)', act: 'ITA 1961', rulesAsOf: 'Budget 2025' },
          { section: '87A', act: 'Rebate', rulesAsOf: 'FY25-26' },
        ],
        stepTraces: [],
      },
    },
  ]);

  const [inputText, setInputText] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);
  const [activeStepTraces, setActiveStepTraces] = useState<AgentStepTrace[]>([]);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, activeStepTraces]);

  const handleSend = async (textToSend?: string) => {
    const prompt = textToSend || inputText;
    if (!prompt.trim() || isProcessing) return;

    setInputText('');
    const userMsgId = `usr-${Date.now()}`;
    const newMsg: ChatMessage = {
      id: userMsgId,
      sender: 'user',
      text: prompt,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    };

    setMessages((prev) => [...prev, newMsg]);
    setIsProcessing(true);
    setActiveStepTraces([]);

    try {
      const response = await AIChatService.sendMessage(
        prompt,
        {
          clientName: activeClient.name,
          pan: activeClient.panMasked,
          inputs: activeClient.taxInputs,
        },
        (steps) => {
          setActiveStepTraces(steps);
        }
      );

      const agentMsg: ChatMessage = {
        id: `agent-${Date.now()}`,
        sender: 'agent',
        agentName: response.agentName,
        text: response.answer,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        structuredResponse: response,
      };

      setMessages((prev) => [...prev, agentMsg]);
    } catch (err) {
      console.error('Chat error:', err);
    } finally {
      setIsProcessing(false);
    }
  };

  const handleFlagForCA = (msgId: string) => {
    setMessages((prev) =>
      prev.map((m) => (m.id === msgId ? { ...m, flaggedForCA: true } : m))
    );
  };

  return (
    <div className="space-y-8">
      {/* Standardized PageHeader */}
      <PageHeader
        title="Agent Chat & Swarm Traces"
        description="Questions answered with statutory citations and mathematical verification. All numbers call our deterministic engine."
        badge={
          <div className="flex items-center gap-2">
            <span className="font-mono text-xs px-2 py-0.5 rounded bg-[var(--surface-raised)] text-[var(--text-secondary)] border border-[var(--hairline)]">
              Assessee: {activeClient.name}
            </span>
            <StatusBadge variant="ai_prepared" label="Multi-Agent Pipeline" />
          </div>
        }
      />

      {/* Guided Client Journey Stepper */}
      <JourneyStepper currentStepId="compute" />

      {/* Next Action Card */}
      <NextActionCard
        title="Need Clarification on HRA vs Home Loan Simultaneous Claims?"
        description="Ask the Agent Swarm to evaluate your rental agreement alongside your provisional housing loan interest certificate to confirm concurrent deduction eligibility."
        actionLabel="Ask About HRA & Home Loan"
        onActionClick={() => handleSend('Can I claim HRA and Home Loan interest simultaneously under the Old Tax Regime?')}
        tone="gold"
        badge="Suggested Query"
      />

      {/* Main Container: Chat Left (8 cols) & Swarm Side-Panel Right (4 cols) */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 h-[72vh]">
        {/* Left: Chat Window (8 cols) */}
        <div className="lg:col-span-8 flex flex-col rounded-2xl bg-[var(--surface)] border border-[var(--border)] shadow-[var(--shadow-soft)] overflow-hidden">
          {/* Messages Scroll Area */}
          <div className="flex-1 overflow-y-auto p-4 sm:p-6 space-y-6">
            {messages.map((msg) => (
              <div
                key={msg.id}
                className={`flex gap-3.5 ${msg.sender === 'user' ? 'justify-end' : 'justify-start'}`}
              >
                {msg.sender === 'agent' && (
                  <div className="w-8 h-8 rounded-xl bg-[var(--surface-raised)] border border-[var(--hairline)] flex items-center justify-center text-[var(--primary-emerald)] shrink-0 mt-1">
                    <Cpu className="w-4 h-4" />
                  </div>
                )}

                <div
                  className={`max-w-2xl rounded-2xl p-4 sm:p-5 text-sm ${
                    msg.sender === 'user'
                      ? 'bg-[var(--primary-emerald)] text-white rounded-tr-none'
                      : 'bg-[var(--surface-raised)] border border-[var(--hairline)] text-[var(--text-primary)] rounded-tl-none'
                  }`}
                >
                  <div className="flex items-center justify-between gap-4 mb-2 text-[11px] font-mono opacity-75">
                    <span>{msg.sender === 'user' ? 'You' : msg.agentName || 'Tax Agent'}</span>
                    <span>{msg.timestamp}</span>
                  </div>

                  {/* Body Text */}
                  <div className="prose prose-invert prose-sm max-w-none leading-relaxed whitespace-pre-line font-sans text-inherit">
                    {msg.text}
                  </div>

                  {/* Grounded Citation Chips & Confidence */}
                  {msg.structuredResponse && msg.sender === 'agent' && (
                    <div className="mt-4 pt-3 border-t border-[var(--hairline)] flex flex-wrap items-center justify-between gap-2 text-xs">
                      <div className="flex flex-wrap items-center gap-1.5">
                        <span className="text-[11px] font-mono text-[var(--text-muted)]">Citations:</span>
                        {msg.structuredResponse.citations.map((c, i) => (
                          <CitationChip key={i} section={c.section} act={c.act} rulesAsOf={c.rulesAsOf} />
                        ))}
                      </div>

                      <div className="flex items-center gap-3">
                        <span className="text-[11px] font-mono text-[var(--primary-emerald)]">
                          {msg.structuredResponse.confidence}% Confidence
                        </span>

                        <button
                          onClick={() => handleFlagForCA(msg.id)}
                          disabled={msg.flaggedForCA}
                          className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-lg text-[11px] font-mono transition-colors ${
                            msg.flaggedForCA
                              ? 'bg-[var(--surface)] text-[var(--semantic-warning)] border border-[var(--semantic-warning)]/40'
                              : 'bg-[var(--surface)] hover:bg-[var(--surface-raised)] text-[var(--text-secondary)] hover:text-[var(--text-primary)] border border-[var(--hairline)]'
                          }`}
                        >
                          <Flag className="w-3 h-3 text-[var(--accent-gold)]" />
                          <span>{msg.flaggedForCA ? 'Flagged for CA' : 'Flag for CA Review'}</span>
                        </button>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            ))}

            {isProcessing && (
              <div className="flex gap-3 justify-start items-center p-3 rounded-xl bg-[var(--surface-raised)] border border-[var(--hairline)] text-xs font-mono text-[var(--primary-emerald)] animate-pulse">
                <Cpu className="w-4 h-4 animate-spin text-[var(--primary-emerald)]" />
                <span>Specialist agents are computing and verifying citations...</span>
              </div>
            )}
            <div ref={messagesEndRef} />
          </div>

          {/* Suggested Prompts Strip */}
          <div className="px-4 py-2 bg-[var(--surface-raised)] border-t border-[var(--border)] overflow-x-auto flex gap-2">
            {SUGGESTED_PROMPTS.map((p, idx) => (
              <button
                key={idx}
                onClick={() => handleSend(p)}
                className="px-3 py-1 rounded-xl bg-[var(--surface)] hover:bg-[var(--surface-raised)] text-[var(--text-secondary)] hover:text-[var(--text-primary)] text-[11px] font-mono whitespace-nowrap transition-colors border border-[var(--hairline)]"
              >
                {p}
              </button>
            ))}
          </div>

          {/* Chat Input Bar */}
          <div className="p-4 bg-[var(--surface)] border-t border-[var(--border)] flex items-center gap-3">
            <input
              type="text"
              placeholder="Ask about regime savings, Section 80CCD, or upload queries..."
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleSend()}
              disabled={isProcessing}
              className="flex-1 bg-[var(--surface-raised)] border border-[var(--hairline)] rounded-xl px-4 py-3 text-sm text-[var(--text-primary)] placeholder-[var(--text-muted)] font-sans outline-none focus:border-[var(--accent-gold)]"
            />
            <button
              onClick={() => handleSend()}
              disabled={isProcessing || !inputText.trim()}
              className="px-5 py-3 rounded-xl bg-[var(--primary-emerald)] hover:bg-[var(--primary-emerald-hover)] disabled:opacity-50 text-white font-mono text-xs font-medium flex items-center gap-2 transition-all shadow-[var(--shadow-soft)]"
            >
              <span>Execute</span>
              <Send className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>

        {/* Right: Agent Activity Swarm Side-Panel (4 cols) */}
        <div className="lg:col-span-4 rounded-2xl bg-[var(--surface)] border border-[var(--border)] shadow-[var(--shadow-soft)] p-5 flex flex-col justify-between overflow-hidden">
          <div className="overflow-y-auto space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-[var(--border)]">
              <div className="flex items-center gap-2">
                <Cpu className="w-4 h-4 text-[var(--primary-emerald)]" />
                <h3 className="font-serif text-base font-medium text-[var(--text-primary)]">
                  Agent Swarm Activity
                </h3>
              </div>
              <span className="text-[10px] font-mono text-[var(--primary-emerald)]">6 Active</span>
            </div>

            {/* Specialist Agents Directory */}
            <div className="space-y-2">
              {[
                { name: 'Document Agent', role: 'OCR extraction, PDF schedules, layout parser' },
                { name: 'Profile Agent', role: 'Assessee income type & regime preference' },
                { name: 'Tax Engine Agent', role: 'Deterministic math (/src/lib/taxEngine.ts)' },
                { name: 'Compliance Agent', role: '26AS, AIS, Section 43B(h), VDA checks' },
                { name: 'Verifier Agent', role: 'Citations & engine output parity checker' },
                { name: 'CA Copilot', role: 'Working paper synthesis & CA sign-off formatting' },
              ].map((agent, i) => (
                <div
                  key={i}
                  className="p-2.5 rounded-xl bg-[var(--surface-raised)] border border-[var(--hairline)] flex items-start gap-2.5 text-xs"
                >
                  <div className="w-2 h-2 rounded-full bg-[var(--primary-emerald)] mt-1 shrink-0" />
                  <div>
                    <div className="font-medium text-[var(--text-primary)] font-mono text-[11px]">{agent.name}</div>
                    <div className="text-[10px] text-[var(--text-muted)]">{agent.role}</div>
                  </div>
                </div>
              ))}
            </div>

            {/* Live Step Traces */}
            <div className="pt-3 border-t border-[var(--border)]">
              <span className="text-[11px] font-mono uppercase tracking-wider text-[var(--text-muted)] block mb-2">
                Execution Pipeline Trace
              </span>
              <div className="space-y-2 max-h-56 overflow-y-auto">
                {(activeStepTraces.length > 0
                  ? activeStepTraces
                  : [
                      {
                        step: '1. Ingestion',
                        agentName: 'Document Agent',
                        status: 'completed',
                        durationMs: 140,
                        confidence: 99,
                        description: 'Ingested Form 16 Part A/B and HDFC Home loan provisional certificate.',
                      },
                      {
                        step: '2. Deterministic Run',
                        agentName: 'Tax Engine Agent',
                        status: 'completed',
                        durationMs: 90,
                        confidence: 100,
                        description: 'Ran /src/lib/taxEngine.ts with FY 2025-26 statutory tax slabs.',
                      },
                      {
                        step: '3. Grounding Verification',
                        agentName: 'Verifier Agent',
                        status: 'completed',
                        durationMs: 110,
                        confidence: 98,
                        description: 'Verified citations against Finance Act 2024. Numbers verified 100%.',
                      },
                    ]
                ).map((t, idx) => (
                  <div key={idx} className="p-2.5 rounded-xl bg-[var(--surface-raised)] border border-[var(--hairline)] text-[11px] font-mono">
                    <div className="flex items-center justify-between text-[var(--text-primary)]">
                      <span className="font-semibold text-[var(--primary-emerald)]">{t.agentName}</span>
                      <span className="text-[10px] text-[var(--text-muted)]">{t.durationMs}ms</span>
                    </div>
                    <p className="text-[var(--text-secondary)] text-[10px] mt-1 leading-normal font-sans">
                      {t.description}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          </div>

          <div className="pt-3 border-t border-[var(--border)] text-[11px] font-mono text-[var(--text-muted)] flex items-center justify-between">
            <span>LLM Never Computes Tax</span>
            <span className="text-[var(--primary-emerald)]">Deterministic Verified</span>
          </div>
        </div>
      </div>
    </div>
  );
};
